/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyAccordion {
    'color': string;
    'description': string;
    'label': string;
    'width': string;
  }
}

declare global {


  interface HTMLMyAccordionElement extends Components.MyAccordion, HTMLStencilElement {}
  var HTMLMyAccordionElement: {
    prototype: HTMLMyAccordionElement;
    new (): HTMLMyAccordionElement;
  };
  interface HTMLElementTagNameMap {
    'my-accordion': HTMLMyAccordionElement;
  }
}

declare namespace LocalJSX {
  interface MyAccordion extends JSXBase.HTMLAttributes<HTMLMyAccordionElement> {
    'color'?: string;
    'description'?: string;
    'label'?: string;
    'onOnToggle'?: (event: CustomEvent<any>) => void;
    'width'?: string;
  }

  interface IntrinsicElements {
    'my-accordion': MyAccordion;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


